sonar.projectKey=albertocavalcante_starlark-syntax-go
sonar.organization=albertocavalcante
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/vendor/**,**/*_test.go,**/testdata/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
